"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './NavBar/NavBar'
import { useRouter } from 'next/router'
import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
//! navbar func


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const path = usePathname()
  const condition = () => {
    if (path === "/" || path === "/SignUp") {
      return
    } else return <NavBar />
  }
  return (
    <html lang="en">

      <body className={inter.className}>
        {condition()}
        {children}</body>
    </html>
  )
}
