"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './NavBar/NavBar'
import { usePathname, useSearchParams } from 'next/navigation'
import { activationcode } from "./confirm/[activationCode]/page"

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
//! navbar func


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const path = usePathname()

  const condition = () => {
    if (path === "/" || path === "/SignUp" || path === "/confirm" || path === `/confirm/${activationcode.substring(9)}` || path === "/Payment" || path === "/Payment/Success" || path === "/Payment/Fail") {
      return
    } else return <NavBar />
  }
  return (
    <html lang="en">

      <body className={inter.className}>
        {condition()}
        {children}</body>
    </html>
  )
}
